name: Build and Deploy React App via OIDC + S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write       # Required for GitHub OIDC
  contents: read        # Required to checkout repo

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Set environment variables for React
      - name: Set environment variables
        run: |
          echo "REACT_APP_API_BASE_URL=https://crm.myapp.com/v1" >> .env
          echo "SOCKET_URL_LIVE=https://crm.myapp.com/v1" >> .env
          echo "PORT=5001" >> .env
          echo "MAINTENANCE_MODE=false" >> .env

      # Build React app
      - name: Build React app
        run: CI=false npm run build

      # Upload build folder as artifact for later use
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build/

  deploy:
    name: Deploy to EC2 via SSM
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download the build artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: build

      # Zip the build folder
      - name: Zip build
        run: |
          cd build
          zip -r ../build.zip .
          cd ..

      # Configure AWS credentials via OIDC
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::8412003453452345:role/Github-pipeline-to-ec2
          aws-region: us-east-1
          role-session-name: github-oidc-session

      # Upload build.zip to S3
      - name: Upload build to S3
        run: |
          aws s3 cp build.zip s3://bucket-name/react/prod-build.zip

      # Deploy to EC2 using SSM (downloads from S3)
      - name: Deploy via SSM
        run: |
          INSTANCE_ID="i-0f0asdfasdfasdfasdf"  # Replace with your EC2 instance ID
          S3_PATH="s3://bucket-name/react/prod-build.zip"
          TARGET_DIR="/home/ubuntu/Builds/Main/FrontBuild/"

          COMMAND_ID=$(aws ssm send-command \
            --targets "Key=instanceIds,Values=$INSTANCE_ID" \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy React Frontend (Main)" \
            --parameters "commands=[
              \"mkdir -p $TARGET_DIR\",
              \"aws s3 cp $S3_PATH $TARGET_DIR/build.zip\",
              \"cd $TARGET_DIR\",
              \"unzip -o build.zip\",
              \"rm build.zip\",
              \"bash /home/ubuntu/DeploymentScripts/main/mainFrontgit.sh\"
            ]" \
            --query "Command.CommandId" \
            --output text \
            --region ap-south-1)

          echo "SSM Command sent: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id $COMMAND_ID \
            --instance-id "$INSTANCE_ID" \
            --region us-east-1

          aws ssm get-command-invocation \
            --command-id $COMMAND_ID \
            --instance-id "$INSTANCE_ID" \
            --region us-east-1
